# action.yml
name: 'witmicko AppSec CodeQL'
description: 'Run witmicko custom CodeQL analysis'
inputs:
  paths-ignored:  
    description: 'Comma-separated list of paths to ignore'
  rules-ignored:
    description: 'Comma-separated list of rules to ignore'
    
runs:
  using: 'composite'
  steps: 
    - name: Generate Config
      run: node scripts/generate-config.js
      env:
        INPUT_PATHS-IGNORED: ${{ inputs.paths-ignored }}
        INPUT_RULES-IGNORED: ${{ inputs.rules-ignored }}
    - name: Initialize CodeQL  
      uses: github/codeql-action/init@v1
      with:
        config-file: ./.github/codeql-config.yml
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v1