# action.yml
# witmicko/Appsec-CodeQL@main
name: 'witmicko AppSec CodeQL'
description: 'Run witmicko custom CodeQL analysis'
inputs:
  paths_ignored:
    description: 'Comma-separated list of paths to ignore in scan'
    required: true
  queries:
    description: 'Appsec qls packs to run' 
    required: true
  languages: 
    description: 'Languages to scan, an array' 
    required: true
  repo:
    description: 'Repository that requested the scan' 
    required: true

env:
  APPSEC_CODEQL_DIR: 'appsec-codeql'

runs:
  using: 'composite'
 
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
      with:
          repository: 'NicholasEllul/Appsec-CodeQL'
          path: ${{ env.APPSEC_CODEQL_DIR }}

    - name: List where user is
      run: pwd
      shell: bash 

    - name: List dirs
      run: ls -lia
      shell: bash 
      
    - name: Enter appsec codeql directory
      run: cd ${{ env.APPSEC_CODEQL_DIR }}
      shell: bash 
    - name: Generate Config
      run: npm i --prod && node scripts/generate-config.js 
      shell: bash 
      env:
        INPUT_PATHS_IGNORED: ${{ inputs.paths_ignored }}
        QUERIES: ${{ inputs.queries }}
        REPO: ${{inputs.repo}}
    - name: Leave appsec codeql directory
      run: cd ..
      shell: bash 
      
    - name: Initialize CodeQL  
      uses: github/codeql-action/init@v2
      with:
        config-file: cd ${{ env.APPSEC_CODEQL_DIR }}/.github/codeql-config.yml
        languages: ${{ inputs.languages }}
    - name: Run CodeQL Analysis
      id: codeql-analysis
      uses: github/codeql-action/analyze@v2
      with:
        upload: false
    - name: Check outputs
      shell: bash
      run: |
        echo "DB Locations: ${{ steps.codeql-analysis.outputs.db-locations }}"
        echo "SARIF Output: ${{ steps.codeql-analysis.outputs.sarif-output }}"
        echo "SARIF ID: ${{ steps.codeql-analysis.outputs.sarif-id }}"
    - name: Echo SARIF
      shell: bash
      env:
        sarif_file: ${{ steps.codeql-analysis.outputs.sarif-output }}
      run: |
        ls $sarif_file
        cd $sarif_file
        find . -maxdepth 1 -type f -exec cat {} +


    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.codeql-analysis.outputs.sarif-output }}
        category: metamask-codeql
