# action.yml
# witmicko/Appsec-CodeQL@main
name: 'witmicko AppSec CodeQL'
description: 'Run witmicko custom CodeQL analysis'
inputs:
  paths-ignored:
    description: 'Comma-separated list of paths to ignore in scan'
    required: true
  rules-ignored:
    description: 'Comma-separated list of rule IDs to ignore' 
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3
      with:
          repository: 'witmicko/Appsec-CodeQL@main'


    # - name: Now Calling the Node action in directory ./actions/node-action
    #   uses: ./actions/node-action
    #   with:
    #     input1: ${{ inputs.input1 }} 
    # - uses: actions/setup-node@v3.6.0
    #   with:
    #     node-version: 16

    # - name: Install Dependencies
    #   run: npm i
    #   shell: bash 

    - name: Generate Config
      run: node scripts/generate-config.js
      shell: bash 
      env:
        INPUT_PATHS-IGNORED: ${{ inputs.paths-ignored }}
        INPUT_RULES-IGNORED: ${{ inputs.rules-ignored }}
    # - name: Initialize CodeQL  
    #   uses: github/codeql-action/init@v1
    #   with:
    #     config-file: ./.github/codeql-config.yml
    # - name: Run CodeQL Analysis
    #   uses: github/codeql-action/analyze@v1