# action.yml
# witmicko/Appsec-CodeQL@main
name: 'witmicko AppSec CodeQL'
description: 'Run witmicko custom CodeQL analysis'
inputs:
  paths_ignored:
    description: 'Comma-separated list of paths to ignore in scan'
    required: true
  rules_ignored:
    description: 'Comma-separated list of rule IDs to ignore' 
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3
      with:
          repository: 'witmicko/Appsec-CodeQL'
    - name: Echo the input paths_ignored
      shell: bash
      env:
        INPUT_PATHS_IGNORED: ${{ inputs.paths_ignored }}
        INPUT_RULES_IGNORED: ${{ inputs.rules_ignored }}
      run: |
        echo "The input $INPUT_PATHS_IGNORED"
        echo "The input is: $INPUT_RULES_IGNORED"
    - name: Generate Config
      run: npm i --prod && node scripts/generate-config.js
      shell: bash 
      env:
        INPUT_PATHS_IGNORED: ${{ inputs.paths_ignored }}
        INPUT_RULES_IGNORED: ${{ inputs.rules_ignored }}
    - name: Initialize CodeQL  
      uses: github/codeql-action/init@v2
      with:
        config-file: .github/codeql-config.yml
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v1