# https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-a-custom-configuration-file
name: "Test db config, makes it easier to only include relevant files in the db"

paths:
  - ./

paths-ignore:
  - ./codeql-cli
  - ./test